### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by CATower** [doriel/musclehub_abtest#3]
Scores:
Code 4 - You got all the code right, and did a particularly good job formatting code for readability in a bunch of spots. 
Presentation 4 - Slides have a nice layout and are easy to understand.
Hypothesis 2 - Could have more clearly stated null hypothesis and what the chi square tests were trying to determine, but otherwise have a question for each test about what is being asked.
Interpretations 3 - Need to revise the p-value typo, but otherwise got the correct interpretations from each test and advise the company about how to improve.

Overall 13/16 - Meets expectations, Did a pretty good job but could use a bit of clarification and cleaning up a typo. The code portion is fantastic however. Congratulations completing the Intensive!

**Comment by doriel** [comment]
Thanks @towerscience
